version: "3.9"

services:
  # shortlinks.service:
  #   container_name: shortlinks.service
  #   build:
  #     context: ../
  #   image: shortlinks.service:dev
  #   restart: unless-stopped
  #   environment:
  #     - NODE_ENV=production
  #     - SL_SERVICE__PORT=5000
  #     - SL_SERVICE__MONGO_URL=mongodb://dev:dev@10.5.0.10:27017/
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     shortlinks.network:
  #       ipv4_address: 10.8.0.2

  shortlinks.infra.data:
    container_name: shortlinks.infra.data
    image: mongo:7.0.4
    restart: unless-stopped
    volumes:
      - ./.mount/data:/data/db
    ports:
      - "5010:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    networks:
      shortlinks.network:
        ipv4_address: 10.8.0.10

  shortlinks.infra.data.console:
    container_name: shortlinks.infra.data.console
    image: mongo-express:1.0.0-20-alpine3.18
    restart: unless-stopped
    ports:
      - "5011:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev
      ME_CONFIG_MONGODB_URL: mongodb://dev:dev@10.8.0.10:27017/
    networks:
      shortlinks.network:
        ipv4_address: 10.8.0.11

networks:
  shortlinks.network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1